version : '3'
services:
  web:
    image: 'redis' 
  node-app:
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    ports:
     - '3000:3000'
    volumes:
      - usr/app/node_modules
      - .:/usr/app
